name: Integration test

env:
  version: 9.2.1

on:
  push:

jobs:

  integration-test:
    runs-on: ${{ matrix.runs-on }}
    name: Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        runs-on: [macos-latest-large]  # ubuntu-22.04, windows-latest, 
    steps:
      - uses: actions/checkout@v5

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install SCIPOptSuite (Linux)
        if: runner.os == 'Linux'
        run: |
          wget --quiet --no-check-certificate https://github.com/scipopt/scip/releases/download/$(echo "v${{env.version}}" | tr -d '.')/SCIPOptSuite-${{ env.version }}-Linux-ubuntu22.deb
          sudo apt-get update && sudo apt install -y ./SCIPOptSuite-${{ env.version }}-Linux-ubuntu22.deb

      - name: Install SCIPOptSuite (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        env:
          SCIPOPTDIR: C:\scipoptdir
        run: |
          $url = "https://github.com/scipopt/scip/releases/download/$(echo "v${{env.version}}" | tr -d '.')/SCIPOptSuite-${{ env.version }}-win64.exe"
          Invoke-WebRequest -Uri $url -OutFile scipopt-installer.exe
          Start-Process -FilePath .\scipopt-installer.exe -ArgumentList "/S", "/D=${{ env.SCIPOPTDIR }}" -Wait
          Add-Content -Path $env:GITHUB_ENV -Value "SCIPOPTDIR=${{ env.SCIPOPTDIR }}"

      - name: Install SCIPOptSuite (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install tbb boost bison
          curl -L -o SCIPOptSuite-${{ env.version }}-Darwin.sh https://github.com/scipopt/scip/releases/download/$(echo "v${{env.version}}" | tr -d '.')/SCIPOptSuite-${{ env.version }}-Darwin.sh
          chmod +x SCIPOptSuite-${{ env.version }}-Darwin.sh
          ./SCIPOptSuite-${{ env.version }}-Darwin.sh --skip-license --include-subdir
          mv SCIPOptSuite-${{ env.version }}-Darwin ${{ github.workspace }}/scipoptsuite
          echo "SCIPOPTDIR=${{ github.workspace }}/scipoptsuite/" >> $GITHUB_ENV
          echo "DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}:${{ github.workspace }}/scipoptsuite/lib" >> $GITHUB_ENV

      - name: Install PySCIPOpt
        run: |
          python -m pip install --upgrade pip
          python -m pip install .

      - name: Install test dependencies
        run: |
          python -m pip install --group test

      - name: Run pyscipopt tests
        env:
          SCIPOPTDIR: ${{ env.SCIPOPTDIR }}
          DYLD_LIBRARY_PATH: ${{ env.DYLD_LIBRARY_PATH }}
        run: pytest -nauto
